### PR TITLE
Expose transaction object

### PR DESCRIPTION
**Pull request by VinceG**
addresses #50

### CODE REVIEW

**Comment by VinceG** [comment]
No test changes or additions were needed for this one.

**Comment by delatbabel** [comment]
@judgej I'm leaving this to you if that's OK. You're listed as the maintainer. There are issues with the test cases found by travis.

**Comment by judgej** [comment]
Thanks. Previously, failed transactions would have returned a null result, which was not helpful because a failed transaction still contains useful data. All these failed tests are looking for the null, when they should now be expecting a transaction detail of some sort. So the tests do need amending.

This is of course, changed functionality that may affect implementations, so needs to be spelled out clearly in the docs too IMO.

@VinceG would you be able to take a look at the tests that are failing?

**Comment by VinceG** [comment]
@judgej Yes. i'll add those changes to the PR today.

Should i add the notes in the documentation as well? There should be also some sort of a change log since this can possibly be a breaking change for some users.

On a side note, Travis does not run the tests against PHP 7, can we add that?

Thanks.

**Comment by judgej** [comment]
Thanks, much appreciated.

It's a good point about the change log. We generally just add notes to releases in github, but that doesn't get into the released code. For now, a note in the README.md would be good.

I was trying to see if we could support the old and new behaviour through some kind of switch, but that's probably just going to overcomplicate things. Just fix, *potentially* break, and provide enough information to help fix any issues quickly. TBH I don't think anyone *should* be checking for a null as the transaction result, but you never know.

If you are running okay on PHP 7 now, and [want to add it](https://github.com/thephpleague/omnipay-authorizenet/blob/master/.travis.yml), then go for it and we'll see how it works :-)

**Comment by VinceG** [comment]
@judgej Sounds good i'll take care of that. We are using PHP 7 (7.0.8 to be exact) and everything working just fine. I'll add that to the yaml files as a PR request as  well.

**Comment by judgej** [comment]
If that's a separate PR, we should see the results immediately.

**Comment by VinceG** [comment]
@judgej the tests now all pass. i've also included PHP 7.0 to travis yaml file and it passed as well. HHVM failed but it failed before this change.

The only thing left is the note in the readme file, not sure if you want me to phrase it or should you?

I think now its ready for review.

Thanks.

**Pull request merged**
