### PR TITLE
Add getTransactionId

### PR DESCRIPTION
**Pull request by jeremib**
Add method AIMResponse::getTransactionId to return the authorize.net transaction id.

### CODE REVIEW

**Comment by barryvdh** [comment]
Is this the id generated by the gateway, or the one you passed when creating?

**Comment by judgej** [comment]
It's the reference generated by the gateway. It is also available in `getTransactionReference ()` which is a compound reference.

I really dislike these compound references, but omnipay makes a point of using a single reference string when releasing or cancelling payment authorisations. There has to be a better way to handle that?

**Comment by judgej** [comment]
@jeremib the `transactionReference` is reserved in OmniPay for the reference that is generated by the gateway, and `transactionId` is the ID that is generated locally by the merchant site. Your change mixes up these two things.

The `transactionReference` that OmniPay gives you will be a compound JSON serialised string containing all the data items that will be needed to capture the authorized amount. You would pass the complete string back to OmniPay when capturing.

If you want the raw `transid` data from the gateway, then it is available in the data from `$response->getData()` and also in the array returned by `$response->getTransactionReference(false)`.

**Comment by jeremib** [comment]
The `\Omnipay\Common\Message\AbstractResponse::getTransactionId` comment says: 

> Get the transaction ID as generated by the merchant website.

How is this not the same as the [Authorize.net Transaction Id](https://support.authorize.net/authkb/index?page=content&id=GL192&actp=LIST)?

> A unique identification value assigned to each transaction processed through the payment gateway. This ID may be used to search for or sort transactions.

**Comment by barryvdh** [comment]
You are the Merchant. When the merchant generates it: transactionId, when the gateway generate is: transactionReference.

**Comment by jeremib** [comment]
Ahhh, got it now.  Thanks for clarifying.

**Comment by barryvdh** [comment]
We should really make this more obvious, not the first time this comes up ;)

**Comment by judgej** [comment]
It's [mentioned here](custom/modules/CSL_ContBookDocs/language/en_us.lang.php) but I guess gets lost in the words. Needs more pictures.

**Comment by judgej** [comment]
I'll close this, as the `transId` is correctly available in the response as the `transactionReferece`.

**Pull request closed without merging**
