### PR TITLE
Issue 93

### PR DESCRIPTION
**Pull request by samlitowitz**
Address [issue 93](https://github.com/thephpleague/omnipay-authorizenet/issues/93).

### CODE REVIEW

**Comment by samlitowitz** [comment]
You are correct @judgej . I have updated the `getData` function to properly order request fields.

**Comment by judgej** [comment]
The additional spaces in [this line](https://github.com/samlitowitz/omnipay-authorizenet/blob/cea163464a31bd0f0a40e4f836602a05235d178d/src/Message/AIMCaptureOnlyRequest.php#L27) are failing the travis tests.

**Comment by judgej** [comment]
Thank you for your effort and patience. This package is improved, I have learnt more about this API that has now fed into another, separate package, and we should end up with improved official documentation for this gateway, Win all around.

**Comment by judgej** [comment]
Let me know when you have checked `dev-master` works for you in the field, and I'll make a new release.

**Comment by samlitowitz** [comment]
Sandbox mode testing work as expected.

**Pull request merged**
