### PR TITLE
Add getters and setters for hashSecret, 

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
hashSecret is an optional authorization parameter

### CODE REVIEW

**Comment by judgej** [comment]
Since the SIM gateway extends the AIM gateway, and the SIM gateway already has these setters and getters, would you like to remove them from the SIM gateway, since they are now redundant there?

**Comment by eileenmcnaughton** [comment]
Done

**Comment by eileenmcnaughton** [comment]
@judgej just revisiting this - looks like I fixed in response to your feedback

**Comment by judgej** [comment]
Now merged. Thank you, and sorry for neglecting this for so long. I'll write a test for it now.

**Comment by eileenmcnaughton** [comment]
Thanks!

**Pull request merged**
