### PR TITLE
CIM Add ability to create Customer Profile with OpaqueData from Accept.js

### PR DESCRIPTION
**Pull request by alberto1el**
I made an example app that showcases the accept.js and this addition that you can check here: 

https://github.com/alberto1el/omnipay-example

### CODE REVIEW

**Comment by judgej** [comment]
Yes, I think this is the problem. I've made a fix and will merge it into `master`.

**Comment by judgej** [comment]
Try pulling in the `master` branch now. Should be fixed. I assumed it would be affecting other people running tests, so got the fix (hopefully :crossed_fingers:) in quickly. Merry Christmas :-)

**Comment by alberto1el** [comment]
@judgej Yes it was that, great catch thank you very much!
I am just missing a couple tests I will add them later on today, I will since I do want this to be merged as soon as possible :)

**Comment by judgej** [comment]
Just a heads up though - the CIM Abstract Request class extends the AIM Abstract Request, and that already supports some of the Opaque Data methods you have added (if I'm reading them correctly). It may be worth checking if duplicate and redundant methods have been been added here.

**Comment by alberto1el** [comment]
@judgej Thanks.
Yes, the methods were being duplicated so I removed them, I actually had copied them from that commit but didn't realize that the CIMAbstractRequest was extending it.

I added the tests and added an example to the README file I hope it is clear enough.

**Comment by judgej** [comment]
Looks great, thank you.

I'm going to try to merge in a few more PRs, but give the master branch a try in the meantime. If all is working for you, we can release this as version 3.1.0

**Comment by alberto1el** [comment]
I tested the master branch with the merged PR and it's working great :)

And yes I have been using this driver for years now, I believe 2019 will be a good year for cleaning it up, I read the really long issue were you talk about the accept.js library and the 'changes' on the Autorize.net API were that guy from authorize.net also comments, and I was wondering, which is the 'roadmap' for this library? , since I saw you worked on a couple repositories (probably to be able to use omnipay 3 with authorize.net which is now possible), will you continue with those or do you want to clean this one?.

Thank you very much for your work @judgej and may you have a very happy new year!

**Pull request merged**
