### PR TITLE
Migrate to XML API for AIM + CIM support

### PR DESCRIPTION
**Pull request by anushr**
**PR Highlights:**

- Migrates the AIM gateway to use the new and improved XML API. As part of this change, the SIM classes have been completely decoupled from the AIM classes; they used to share some functionality earlier, but that's no longer possible since the endpoints and data format are now very different.

- Added integration tests that actually hit AuthorizeNet. These make me feel a LOT safer when rolling out big changes like this one. Note that these tests only kick in if the following environment variables are set: `AUTHORIZE_NET_API_LOGIN_ID`, `AUTHORIZE_NET_TRANSACTION_KEY`.

- Introduces support for a new CIM gateway (Customer Information Manager) which supports creating cards and customer profiles. Ideally, this should have been a separate PR, but #6 (the original PR for migrating to the XML API) got quite stale over time and too much CIM work had been done to backtrack now and split it up.

Note: This PR replaces #6.

### CODE REVIEW

**Comment by delatbabel** [comment]
Looks good to me. Can someone who actually has gateway keys verify that this actually works in the real world? The PR that this replaces has been tossed around for a while so I think it's time we considered merging this.

**Comment by judgej** [comment]
Was hoping to look at this sooner, but got dragged into other things this weekend. I can look at this from the DPM view first, then work backwards into SIM, AIM and CIM. I've got codes for this, but generally am only using DPM in production for its easier PCI conformance.

**Comment by anushr** [comment]
Just an FYI, we deployed this to production last Tuesday. So far so good.

**Comment by judgej** [comment]
Thanks.

**Comment by judgej** [comment]
Am I looking at the right branch? The SIM gateway still seems to extend the AIM gateway. I used this to get the branch to test:

    git clone https://github.com/anushr/authorizenet.git xml-api

When submitting a DPM form, this is giving me the following error at `https://apitest.authorize.net/xml/v1/request.api`

~~~json
{
    "messages": 
{
    "resultCode": "Error",
    "message": 
[
            {
                "code": "E00001",
                "text": "Unexpected character encountered while parsing value: x. Path '', line 0, position 0."
            }
        ]
    }
}
~~~

I'm not sure if this is in response to the callback - I'll check.

**Comment by judgej** [comment]
Ah, got it. You changed the AIM endpoints to XML endpoints, but those URLs now filter down to SIM and DPM, for which they don't work as those methods don't use XML. SIM may, but DPM just uses a direct POST so no XML is involved.

If you could modify `SIMGateway::getDefaultParameters()` to set the original endpoints as the default, then we can give it another go. This works for me, but I've not got time to merge it into your PR this evening:

~~~php
    public function getDefaultParameters()
    {
        $parameters = parent::getDefaultParameters();
        $parameters['hashSecret'] = '';
        $parameters['liveEndpoint'] = 'https://secure2.authorize.net/gateway/transact.dll';
        $parameters['developerEndpoint'] = 'https://test.authorize.net/gateway/transact.dll';

        return $parameters;
    }
~~~

**Comment by anushr** [comment]
@judgej I've fixed the endpoints for SIM & DPM

**Comment by judgej** [comment]
Thanks - that's DPM working for me again. Will try SIM next.

**Comment by judgej** [comment]
Finally got around to testing SIM with my test account. All works without a hitch.

How's your production instance going? Any changes needed, or is it just ticking along taking payments? I'll merge if there are no further changes or surprises you've found in production.

**Comment by anushr** [comment]
Awesome! 

AIM & CIM have been working smoothly in production. No issues whatsoever. Pleasantly surprised :)

**Comment by aditya-cherukuri** [comment]
Would be nice if deleteCard is supported for CIM.

**Comment by judgej** [comment]
Sorry for the delay in merging - just up to my neck in all sorts here :-)

Would you like to give dev-master a try to confirm it all looks okay to you. I'll do the same this end on a test site.

**Comment by anushr** [comment]
Nice!

I gave dev-master a whirl. Works fine locally and all the functional tests in our application passed. So looks good to me.

**Comment by aditya-cherukuri** [comment]
I have tried the AIM and CIM gateways with sandbox accounts I was successful in performing transactions.

**Comment by judgej** [comment]
Thanks. Just finding the time to try it on my DPM UAT system, then we can go for a release.

**Comment by judgej** [comment]
Works fine on my UAT system using DPM.

**Pull request merged**
