### PR TITLE
Handle XML to JSON array conversion issue when a single payment profile is present

### PR DESCRIPTION
**Pull request by anush**
`CIMGetProfileResponse::getMatchingPaymentProfileId` fails when the response contains only a single payment profile.

### CODE REVIEW

**Comment by judgej** [comment]
Great work! I'll aim to get this installed today and into a release quickly, since it fixes a problem with no easy workaround.

**Comment by judgej** [comment]
Thank you.

**Comment by anush** [comment]
Yay! Thanks for the quick flip @judgej

**Comment by judgej** [comment]
You had all the tests, and it was short and sweet, and that makes it easy :-)

**Pull request merged**
