### PR TITLE
Using the XML API for AIM gateway

### PR DESCRIPTION
**Pull request by anushr**
Moves the AIM gateway over to the new and improved XML API. 

I tried to leave most unit tests untouched to ensure the least amount of potential breakage, but some had to be tweaked since this was a significant overhaul. 

As part of this change, the SIM classes have been completely decoupled from the AIM classes; they used to share some functionality earlier, but that's no longer possible since the endpoints and data format are now very different.

### CODE REVIEW

**Comment by jamesa** [comment]
:+1: is this just waiting on merge conflicts?

**Comment by kayladnls** [comment]
That is one of the issues, yes. This is a very substantial PR that requires some pretty in depth vetting to merge. I apologize for the delay.

**Comment by anushr** [comment]
Merge conflicts resolved

**Comment by judgej** [comment]
This has been hanging around for a while, and does have a lot of hard work in it. The other gateway types (DPM and SIM) extend from AIM, so we need to make sure this change is not going to break those. Has anybody here got any experience of AIM?

**Comment by anushr** [comment]
@judgej Thanks for picking this back up. 

I'm actually in the process of making another substantial overhaul. You may have noticed that this PR also brings in support for CIM (ability to save customer profiles and credit cards). Originally, AIM and CIM were quite different, but now Auth.Net has done some pretty good consolidation of the two. They both now share common endpoints and payload for the basic actions (auth, capture, refund, void) -- which was not the case before. So I'm trying to refactor the code such that those actions have shared logic.

I'd suggest holding off on this PR for another week or so; I'm pretty close to finishing the refactoring.

> The other gateway types (DPM and SIM) extend from AIM, so we need to make sure this change is not going to break those

What's been done here should not affect DPM or SIM. The abstract classes that they extended from have not been altered in content; just renamed.

**Comment by judgej** [comment]
Awsome :-)

**Comment by anushr** [comment]
@judgej @kayladnls I'm closing this in favor of #34

**Pull request closed without merging**
